### ISSUE TITLE
if freshly installed moodle complains that the rsd plugin is misplaced

### ISSUE THREAD

**Issue by phish108** [arael/moodle_rsd#2]
The component installs correctly but at the first call moodle complains that the plugin is misplaced. 

After assigning " local_moodle_rsd" to the component in version.php the error disappeared.

**Comment by arael** [comment]
According to the documentation the component value should be correct: https://docs.moodle.org/dev/version.php

I have tried on my local moodle instance and there are no error messages. Moodle 2.9.5+

I think local_rsd as component name is correct. Could not find anywhere in the documentation that that _moodle token is needed.

Could you please let me know where did you find that local plugins have to be named local_moodle_* ?

**Comment by arael** [comment]
I think I know why you got that error. You have cloned the directory to local/moodle_rsd.

Though the installation instructions are:

> Clone the code in the MOODLE_ROOT/local/rsd directory and check the Notifications page as administrator.
